### ISSUE TITLE
Command to enable LintLens on files not named `.eslintrc`

### ISSUE THREAD

**Issue by darahak** [ghmcadams/vscode-lintlens#10]
I have use cases where my config files are not name `.eslintrc` and I have no way to use the extension manually on them.

I would love to be able to run LintLens from the command palette.

What do you think?

**Comment by ghmcadams** [comment]
Hey @darahak,

This is not something I have considered.  I know its possible and will try to find some time to look into it.  I am open to looking at PRs if you're interested in taking a look at this yourself.

Gabriel

**Comment by darahak** [comment]
@ghmcadams I don't have experience with VS Code extensions, but I'll take a look.
I just had to ask first if this feature made sense.
