### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by benubach** [ghmcadams/vscode-lintlens#12]
- Issue Type: `Performance`
- Extension Name: `lintlens`
- Extension Version: `2.3.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.34.0`

CPU Profile: [ghmcadams.lintlens-unresponsive.cpuprofile.txt](https://github.com/ghmcadams/vscode-lintlens/files/3233622/ghmcadams.lintlens-unresponsive.cpuprofile.txt)

**Comment by ghmcadams** [comment]
I'm sorry.  I have no idea how to fix this while keeping an important feature.  As I understand it, extensions that use webview consume a high amount of CPU.  When you see the popup and click the "more information" link, it will open a webview.  An option you have available is to click the icon to the right of that link, which will open in the browser instead.

Any ideas would be appreciated.
