### ISSUE TITLE
[FEAT] Being able to pass a list of config files in the settings

### ISSUE THREAD

**Issue by teoxoy** [ghmcadams/vscode-lintlens#20]
It would be great if I could specify a list of eslint config files in the plugin settings.

I usually have 4 config files:

```
.eslintrc.yml          <-- main file
.eslint.base.yml       <-- base rules
.eslint.import.yml     <-- import rules
.eslint.typescript.yml <-- ts rules
```

**Comment by ghmcadams** [comment]
Hello,

While I understand the desire for this feature, it would be a low priority feature, given the effort vs reward for most people.  I am open to PRs, if you're interested.

Thank you,
Gabriel
