### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by genoaseguros** [ghmcadams/vscode-lintlens#24]
- Issue Type: `Performance`
- Extension Name: `lintlens`
- Extension Version: `2.8.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Inovação\ghmcadams.lintlens-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ghmcadams** [comment]
I'm sorry. I have no idea how to fix this while keeping an important feature. As I understand it, extensions that use webview consume a high amount of CPU. When you see the popup and click the "more information" link, it will open a webview. An option you have available is to click the icon to the right of that link, which will open in the browser instead.

Any ideas would be appreciated.
