### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rodrigoaraujolima92** [ghmcadams/vscode-lintlens#26]
- Issue Type: `Bug`
- Extension Name: `lintlens`
- Extension Version: `2.8.0`
- OS Version: `Linux x64 5.3.0-46-generic`
- VSCode version: `1.44.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

Unresponsive - Performance Issue 
Startup Activation: 14372ms
Profile: 6817.08ms

**Comment by ghmcadams** [comment]
There is not much I can do with this.  Unless you have more information, I will have to close this issue.
