### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by a7madgamal** [ghmcadams/vscode-lintlens#30]
- Issue Type: `Performance`
- Extension Name: `lintlens`
- Extension Version: `3.0.0`
- OS Version: `Darwin x64 19.5.0`
- VSCode version: `1.45.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/hassanein/ghmcadams.lintlens-unresponsive.cpuprofile.txt
[ghmcadams.lintlens-unresponsive.cpuprofile.txt](https://github.com/ghmcadams/vscode-lintlens/files/4753211/ghmcadams.lintlens-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by a7madgamal** [comment]
[ghmcadams.lintlens-unresponsive.cpuprofile.txt](https://github.com/ghmcadams/vscode-lintlens/files/4753213/ghmcadams.lintlens-unresponsive.cpuprofile.txt)

**Comment by Crystal-RainSlide** [comment]
LintLens `v3.0.3` on VSCodium `v1.72.0` on Windows 10

[ghmcadams.lintlens-unresponsive.cpuprofile.txt](https://github.com/ghmcadams/vscode-lintlens/files/9757548/ghmcadams.lintlens-unresponsive.cpuprofile.txt)
