### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rsamala-osius** [ghmcadams/vscode-lintlens#4]
- Issue Type: `Performance`
- Extension Name: `lintlens`
- Extension Version: `2.3.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/admin/ghmcadams.lintlens-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ghmcadams** [comment]
@rsamala-osius This is very vague.  Can you give me more information?

**Comment by ghmcadams** [comment]
I am closing this issue due to lack of information and my inability to reproduce.
