### ISSUE TITLE
Rule not found with @rushstack/security/no-unsafe-regexp

### ISSUE THREAD

**Issue by binary64** [ghmcadams/vscode-lintlens#42]
Install `yarn add -DW @rushstack/eslint-plugin-security` npm package,

Then add this to your eslintrc.yml > rules section:
```yml
  "@rushstack/security/no-unsafe-regexp":
    - error
```

And you should see it says "Rule not found", when it is infact there and works.

It works fine for "@rushstack/no-new-null" and `yarn add -DW @rushstack/eslint-plugin`

**Comment by ghmcadams** [comment]
Hi @binary64,

Thanks for creating this issue.  I came across this myself the other day when trying out many shareable configs at work.  The reason this is happening is that my understanding of the structure of a rule name was `<plugin name>/<rule name>` but this has 2 slashes.  If I have time, I can take a look, but I have been really busy lately.

I do welcome PRs though, and if you have time, maybe you can take a look.

**Comment by ghmcadams** [comment]
Fixed with #44
