### ISSUE TITLE
Doesnt work with workspace using yarn pnp (berry)

### ISSUE THREAD

**Issue by vito-giarrusso** [ghmcadams/vscode-lintlens#49]
If i use the newer yarn v2 or v3 with pnp mode activated, this extension fails with the following error. 
```
[exthost] [error] MissingESLintError: Unable to find ESLint within the open folders' node_modules, make sure you've run `npm install` or `yarn`
```

I believe it is caused by the eslint check in [this line of code](https://github.com/ghmcadams/vscode-lintlens/blob/30e5ffbeab670859bce79db7a610fb2f3935ad24/src/eslint.js#L5):
```js
const eslintPackagePath = getWorkspaceDir('./node_modules/eslint');
```
PR incoming with a fix

**Comment by vito-giarrusso** [comment]
Is this project abandoned?
Should i just for the repo and republish under another name?

**Comment by ghmcadams** [comment]
The project is not abandoned.  I am not paid to work on this and have many other things to do.  I work on this free for you and many others, and have no SLA.  Feel free to fork and republish if you feel I am not fast enough.

**Comment by vito-giarrusso** [comment]
> The project is not abandoned.  I am not paid to work on this and have many other things to do.  I work on this free for you and many others, and have no SLA.  Feel free to fork and republish if you feel I am not fast enough.

Whoah sorry man, I didn't mean it to sound that rude...
Just was wondering if it was abandoned is all. 
Thanks for all the work you do buddy, I use this extension all the time :)
