### ISSUE TITLE
Not working in new project still working in other projects

### ISSUE THREAD

**Issue by Luxcium** [ghmcadams/vscode-lintlens#53]
Hello, thanks for your awesome VsCode Extension I do appreciate the time you have put into developing it...

I become reliant on your plugin to be able to add complicated rules in my projects with a lot of eslint-plugin.

I was surprised that it would not be working in a new project folder and I am not sure what I need to do in order to troubleshoot.

I do understand your time is precious (or that your free time might be limited) but I will need to have more instruction in order to give you more details about my configuration to narrow the troubleshooting to what is more relevant to find why it is not working...

**Comment by ghmcadams** [comment]
Hi @Luxcium.  Thanks for creating an issue.  Can you tell me more about your new project and how if differs from the one that works?  Any time one thing works and one doesn't, the reason is in the differences between the 2.

Thank you

**Comment by ghmcadams** [comment]
Closing due to lack of information.
