### ISSUE TITLE
Suggestions for a possible icon for the project.

### ISSUE THREAD

**Issue by Luxcium** [ghmcadams/vscode-lintlens#54]
I do not know if it would make sense

 for you to use one of these as the icon of the project... 

I think your project is worthy of an icon if you do not like my suggestions let me know what could be your preference for an icon logo...

[<img src="https://user-images.githubusercontent.com/42672814/192633817-4f25b280-0e34-4003-bf1c-282911c61fd7.svg" alt="EsLint logo with VSCode colors" width="128" height="128">](https://user-images.githubusercontent.com/42672814/192633817-4f25b280-0e34-4003-bf1c-282911c61fd7.svg)
[<img src="https://user-images.githubusercontent.com/42672814/192633818-99afbefc-07b4-44e7-b24a-89ac92ccb2dc.svg" alt="VSCode logo with EsLint colors" width="128" height="128">](https://user-images.githubusercontent.com/42672814/192633818-99afbefc-07b4-44e7-b24a-89ac92ccb2dc.svg)
 
I only inverted the logo colors so that at least it is not empty.

**Comment by ghmcadams** [comment]
Hi @Luxcium.  Thanks for thinking of this.  I had never thought about the marketing part of creating an extension.  Unfortunately, because those logos look so much like the eslint and vscode logos, I would not feel comfortable using them.
