### ISSUE TITLE
Doesn't work with the new eslint.config.js format 

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [ghmcadams/vscode-lintlens#55]
The extension doesn't currently support the new eslint.config.js format. https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new
Can you add support for it?

**Comment by ghmcadams** [comment]
Hey @AndreaPontrandolfo.  I just published a new version that should work with the new flat config format.  Try it out and let me know if you have any issues.

Thanks

**Comment by AndreaPontrandolfo** [comment]
@ghmcadams 
It doesn't seem to be working for me, but i may have a special usecase. 
This is the file https://github.com/AndreaPontrandolfo/sheriff/blob/master/configs/eslint.config.js
The path is <root>/configs/eslint.config.js

**Comment by ghmcadams** [comment]
Yeah.  That kind of file (more than a simple export of the config) doesn't work.  When I get a chance, I can take a look and see what amount of effort it would take.  I am more than willing to accept PRs if you want to take a look

**Comment by AndreaPontrandolfo** [comment]
>  I am more than willing to accept PRs if you want to take a look

Sure, i'll try as soon as i find the time.
i think this is kind of linked to https://github.com/ghmcadams/vscode-lintlens/issues/51.
The extension should have a setting that let's you declare an array of possible paths where to look for the config file.

Also, can you reopen this issue? @ghmcadams

**Comment by ghmcadams** [comment]
Thanks @AndreaPontrandolfo.  The path is not the issue and this is not related to #51.  Your config file was found, but has a complexity that is currently not supported.

**Comment by ghmcadams** [comment]
As this issue is about support for the new format, but your new request is about the complexity that could exist in configs of either format, please open a new issue to request support for complex config files.
