### ISSUE TITLE
[FEATURE REQUEST] Support for complex eslint.config.js configs

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [ghmcadams/vscode-lintlens#59]
Followup for https://github.com/ghmcadams/vscode-lintlens/issues/55.

## PROBLEM
The extension currently detects and parse a `eslint.config.js` file, but is unable to process more complex usecases.

## ENHANCEMENT
The extension should be able to figure out more complex `eslint.config.js` configurations.

**Comment by ghmcadams** [comment]
@AndreaPontrandolfo I had time to look at this and made some improvements (v6).  Not all of what you shared in your config is supported (variable reassignments and array pushes are a lot more complicated), but most of what you need is there.

**Comment by AndreaPontrandolfo** [comment]
Sorry for the late reply. I just tried it and it works great! I can't believe it, you are awesome! Thanks you!
