### ISSUE TITLE
Remove "Activate on all files"

### ISSUE THREAD

**Issue by JustinGrote** [ghmcadams/vscode-lintlens#69]
![image](https://user-images.githubusercontent.com/15258962/227012375-8ac8919d-d343-45db-a97b-3d4928c12136.png)

This basically makes the others pointless, and always activates your extension and uses resources even if not contextually appropriate. Thanks!

**Comment by ghmcadams** [comment]
Though that is correct (that the others are pointless and could be removed), activating for all files allows the extension to check the file to see if it is an eslint config file that does not use the standard name.  This is common for library developers and shareable config developers as well as many apps developers who use different configs for different scenarios.  I don't believe the resource overhead is too much considering the value of enabling the extension for many more users.
