### ISSUE TITLE
[Bug] need to update the rules

### ISSUE THREAD

**Issue by Ukheon** [ghmcadams/vscode-lintlens#76]
First of all, thank you. I recently downloaded it during eslint setup, used it, and got some help.
There is a warning that rules that exist in eslint cannot be found during use
Please check it out

![issue1](https://github.com/ghmcadams/vscode-lintlens/assets/68854946/122b01dd-bbb5-4789-9474-0ad2c68ee74d)
![issue2](https://github.com/ghmcadams/vscode-lintlens/assets/68854946/e581c50e-0db3-41b5-9789-6ca33f5c6642)
# **That option is a disused option. I'm sorry**

**Comment by Ukheon** [comment]
That option is a disused option. sorry

**Comment by ghmcadams** [comment]
Hi Ukheon.  LintLens gathers the list of rules from your currently installed ESLint version.  The `Rule not found` message for rules that exist usually means that you have not yet installed what is listed in your package.json file.  Run `npm install` and it should show again (you may need to restart your IDE).
