### ISSUE TITLE
Replace deprecated typescript plugin with `@typescript-eslint`

### ISSUE THREAD

**Issue by r0skar** [ghmcadams/vscode-lintlens#8]
The old [eslint-typescript](https://github.com/bradzacher/eslint-plugin-typescript#readme) plugin and parser have been replaced by the [@typescript-eslint](https://github.com/typescript-eslint/typescript-eslint#readme) monorepo. Using these new eslint-typescript packages and your plugin, I get following error `Missing plugin: @typescript-eslint`.

**Comment by ghmcadams** [comment]
Hey @r0skar,

Thanks for bringing this issue to my attention.  Its been a little while since I played with this, and have never played with the typescript plugin specifically.  I will try and find some time to check this out.  If you feel I am not moving fast enough, please reach out - and I'm definitely willing to take a look at any PR you may feel like creating.

**Comment by lvl99** [comment]
I think it might just be a naming format. As you can see from my screenshot below, LintLens is looking for `eslint-plugin-@typescript-eslint`:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/238480/53486461-13491d00-3a89-11e9-84d1-6ce223706961.png">

**Comment by r0skar** [comment]
It is a naming format. The problem is that the plugin assumes every eslint-plugin will start with the same prefix: https://github.com/ghmcadams/vscode-lintlens/blob/57a0c4f92827ec2efbfa351464711d5b87f90afa/constants.js#L21

Maybe add an additional check to see whether `**/node_modules/${pluginName}/package.json` exists before falling back to also check for `${constants.eslintPluginPrefix}${pluginName}`?
https://github.com/ghmcadams/vscode-lintlens/blob/8214aebc476d5109fea4672ac907463e1f2dcf50/eslintManager.js#L73

**Comment by paramsinghvc** [comment]
Facing the same problem. Any update?

**Comment by ghmcadams** [comment]
I have been really busy with work and have not had time to look at this.  I am more than willing to take a look at pull requests if anyone would like to fix this.

**Comment by axmrnv** [comment]
So, no reaction after two weeks. @ghmcadams, should we consider vscode-lintlens abandonware?

**Comment by ghmcadams** [comment]
Sorry, @axmrnv. I didn’t even notice the PR. I will take a look this evening.

**Comment by ghmcadams** [comment]
@axmrnv I reviewed your PR.  Please address the minor changes I requested and I can merge/publish right away

**Comment by axmrnv** [comment]
Hm, I didn't see notifications from GitHub as well, I've found out about the new version from the Twitter, thanks for mentioning. :)
