### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by WenzheFan** [ghmcadams/vscode-lintlens#9]
- Issue Type: `Performance`
- Extension Name: `lintlens`
- Extension Version: `2.3.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/lilei/ghmcadams.lintlens-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ghmcadams** [comment]
Hey,

Thanks for the information.  Unfortunately, without the cpuprofile.txt file that the instructions mentioned, I can do nothing.

Than you,
Gabriel
